---
- name: Setting host facts using complex arguments
  set_fact:
    nexus_url_baseurl: "{{ nexus_default_schema }}://{{ nexus_default_host }}:{{ nexus_default_port }}{{ nexus_default_baseurl }}"

- name: Add realms docker allow to pull
  include_tasks: granted-realms-docker.yaml
  when: nexus_registry_docker_enabled

- name: Add docker registry to nexus-oss
  include_tasks: docker-registry.yaml
  when: nexus_registry_docker_enabled

- name: Setup new user and roles for docker specific registry
  when: 
    - nexus_create_new_user
    - nexus_registry_docker_enabled
  block: 
    - name: Add new roles
      include_tasks: roles.yaml

    - name: Add new users
      include_tasks: users.yaml
      when: nexus_create_new_user

- name: Iptables config docker registry
  when: nexus_registry_docker_enabled
  become: true
  block:
    - name: UFW allow port 8086/8087 tcp
      ufw: 
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "{{ docker_registry_hosted_port }}"
        - "{{ docker_registry_group_port }}"
      when: ansible_facts['os_family'] == 'Debian'
    
    - name: firewall-cmd allow port 8086/8087 tcp
      firewalld: 
        port: "{{ item }}/tcp"
        permanent: yes
        immediate: true
        state: enabled
      loop:
        - "{{ docker_registry_hosted_port }}"
        - "{{ docker_registry_group_port }}"
      when: ansible_facts['os_family'] == 'RedHat'